### ISSUE TITLE
ProduKey@1.96: Hash check failed

### ISSUE THREAD

**Issue by Jojo4GH** [Ash258/Scoop-NirSoft#7]
Hash check failed!
App:         nirsoft/ProduKey
URL:         https://www.nirsoft.net/utils/produkey-x64.zip
First bytes: 80 75 3 4 20 0 2 0
Expected:    4e1ac22dd0c349c1246669df7cfdfd0ce85723a27aa5f5b7c0fdc456c34ccb8b
Actual:      a6b74933c14d767811e57809c333f85691f5facef73bca9b4b17b340bdac14ab

**Comment by Ash258** [comment]
1844abd61a0c0470bddd6763e0d909b0b2c020ca
